import LoewnerS0.S0Univalent

/-!
# Maps with parametric representation are initial elements of Loewner chains

For `f ∈ S⁰(𝔹)` with parametric representation `f = lim eᵗ v(·, t)` we construct the Loewner chain
`F(s, ·) = eˢ f_s`, where `f_s = lim_{τ → ∞} e^τ w_s(·, τ)` is the map generated by the time-shifted
Herglotz vector field `h(s + ·)`. Each `f_s` lies in `S⁰(𝔹) ⊆ S(𝔹)`, the transition property
`f_s = e^{t-s} f_t ∘ w_s(·, t - s)` follows from uniqueness for the Loewner ODE, and the growth
theorem shows that `{e⁻ᵗ F(t, ·)}` is locally bounded. This proves `S⁰(𝔹) ⊆ S⁰'(𝔹)`, one half of
the characterization of Graham–Hamada–Kohr.
-/

open Complex Metric Set Filter MeasureTheory
open scoped InnerProductSpace Topology

noncomputable section

namespace LoewnerS0

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E] [CompleteSpace E]
  [FiniteDimensional ℂ E] {h v : ℝ → E → E} {f : E → E}

/-- **`S⁰(𝔹) ⊆ S⁰'(𝔹)`**: maps with parametric representation are initial elements of Loewner
chains `F` with `{e⁻ᵗ F(t, ·)}` locally bounded [GHK02]. -/
theorem IsParametricRep.mem_classS0' (hf : IsParametricRep f h v) : f ∈ classS0' E := by
  classical
  have hh := hf.herglotz
  have hv := hf.solution
  -- solutions for the shifted fields, and the maps they generate
  have hw : ∀ s : ℝ, ∃ w : ℝ → E → E, 0 ≤ s → IsLoewnerSolution (fun σ => h (s + σ)) w := by
    intro s
    by_cases hs : 0 ≤ s
    · obtain ⟨w, hw⟩ := (hh.shift hs).exists_isLoewnerSolution
      exact ⟨w, fun _ => hw⟩
    · exact ⟨fun _ z => z, fun h' => absurd h' hs⟩
  choose w hw using hw
  have hg : ∀ s : ℝ, ∃ g : E → E, 0 ≤ s → IsParametricRep g (fun σ => h (s + σ)) (w s) := by
    intro s
    by_cases hs : 0 ≤ s
    · obtain ⟨g, hg⟩ := (hw s hs).exists_isParametricRep (hh.shift hs)
      exact ⟨g, fun _ => hg⟩
    · exact ⟨id, fun h' => absurd h' hs⟩
  choose g hg using hg
  set F : ℝ → E → E := fun s z => (Real.exp s : ℂ) • g s z with hF
  have hexp0 : ∀ s : ℝ, (Real.exp s : ℂ) ≠ 0 := fun s => by exact_mod_cast (Real.exp_pos s).ne'
  -- the transition property `F s z = F t (w s (t - s) z)`
  have htrans : ∀ s t : ℝ, 0 ≤ s → s ≤ t → ∀ z ∈ unitBall E,
      F s z = F t (w s (t - s) z) := by
    intro s t hs hst z hz
    have ht : 0 ≤ t := hs.trans hst
    have hts : 0 ≤ t - s := by linarith
    set y := w s (t - s) z with hy
    have hyB : y ∈ unitBall E := (hw s hs).mem_unitBall hz hts
    -- the two curves agree
    have hc := (hw s hs).isLoewnerCurve_shift hz hts
    have hfield : (fun σ => (fun σ => h (s + σ)) (t - s + σ)) = fun σ => h (t + σ) := by
      funext σ; simp only; congr 1; ring
    rw [hfield] at hc
    have hc' : IsLoewnerCurve (fun σ => h (t + σ)) y (fun τ => w t τ y) :=
      fun τ hτ => hw t ht y hyB τ hτ
    have heq : ∀ τ, 0 ≤ τ → w s (t - s + τ) z = w t τ y := fun τ hτ =>
      IsLoewnerCurve.eq (hh.shift ht) hyB hc hc' hτ
    -- pass to the limit
    have h1 : Tendsto (fun τ : ℝ => (Real.exp (t - s + τ) : ℂ) • w s (t - s + τ) z) atTop
        (𝓝 (g s z)) :=
      ((hg s hs).tendsto z hz).comp (tendsto_atTop_add_const_left _ (t - s) tendsto_id)
    have h2 : Tendsto (fun τ : ℝ => (Real.exp (t - s) : ℂ) • ((Real.exp τ : ℂ) • w t τ y))
        atTop (𝓝 ((Real.exp (t - s) : ℂ) • g t y)) :=
      ((hg t ht).tendsto y hyB).const_smul _
    have h3 : g s z = (Real.exp (t - s) : ℂ) • g t y := by
      refine tendsto_nhds_unique h1 (h2.congr' ?_)
      filter_upwards [eventually_ge_atTop 0] with τ hτ
      rw [heq τ hτ, smul_smul, ← Complex.ofReal_mul, ← Real.exp_add]
    simp only [hF]
    rw [h3, smul_smul, ← Complex.ofReal_mul, ← Real.exp_add]
    congr 3
    ring
  refine ⟨F, ⟨?_, ?_, ?_, ?_, ?_⟩, ?_, ?_⟩
  · -- holomorphy
    intro s hs
    exact (hg s hs).differentiableOn.const_smul _
  · -- univalence
    intro s hs z₁ hz₁ z₂ hz₂ heq
    exact (hg s hs).injOn hz₁ hz₂ (smul_right_injective E (hexp0 s) heq)
  · -- `F s 0 = 0`
    intro s hs
    simp [hF, (hg s hs).map_zero]
  · -- `DF(s, 0) = eˢ I`
    intro s hs
    have hd := ((hg s hs).isNormalized.differentiableAt_zero).hasFDerivAt
    rw [(hg s hs).isNormalized.fderiv_zero] at hd
    exact (hd.const_smul (Real.exp s : ℂ)).fderiv
  · -- subordination
    intro s t hs hst
    rintro _ ⟨z, hz, rfl⟩
    exact ⟨w s (t - s) z, (hw s hs).mem_unitBall hz (by linarith), (htrans s t hs hst z hz).symm⟩
  · -- `F 0 = f`
    intro z hz
    have hw0 : IsLoewnerSolution h (w 0) := by
      have := hw 0 le_rfl
      simpa using this
    have huniq : ∀ τ, 0 ≤ τ → w 0 τ z = v τ z := fun τ hτ =>
      hw0.eqOn_of_isHerglotzVF hh hv hτ hz
    have hlim : Tendsto (fun τ : ℝ => (Real.exp τ : ℂ) • w 0 τ z) atTop (𝓝 (g 0 z)) := by
      have := (hg 0 le_rfl).tendsto z hz
      simpa using this
    have hgf : g 0 z = f z := by
      refine tendsto_nhds_unique hlim ((hf.tendsto z hz).congr' ?_)
      filter_upwards [eventually_ge_atTop 0] with τ hτ
      rw [huniq τ hτ]
    simp [hF, hgf]
  · -- local boundedness
    intro r hr
    refine ⟨max r 0 / (1 - max r 0) ^ 2, fun t ht z hz => ?_⟩
    have hz1 : z ∈ unitBall E := mem_unitBall.mpr (lt_of_le_of_lt hz hr)
    have hgt : g t ∈ classS0 E := ⟨_, _, hg t ht⟩
    have hb := (classS0_norm_bounds hgt hz1).2
    have hsimp : (Real.exp (-t) : ℂ) • F t z = g t z := by
      simp only [hF, smul_smul, ← Complex.ofReal_mul, ← Real.exp_add, neg_add_cancel,
        Real.exp_zero, Complex.ofReal_one, one_smul]
    show ‖(Real.exp (-t) : ℂ) • F t z‖ ≤ _
    rw [hsimp]
    refine hb.trans ?_
    have hr' : ‖z‖ ≤ max r 0 := hz.trans (le_max_left _ _)
    have hr1 : max r 0 < 1 := max_lt hr one_pos
    have : 0 < 1 - max r 0 := by linarith
    have h1 : 0 < 1 - ‖z‖ := by linarith [mem_unitBall.mp hz1]
    gcongr

/-- **`S⁰(𝔹) ⊆ S⁰'(𝔹)`** [GHK02]. -/
theorem mem_classS0'_of_mem_classS0 (hf : f ∈ classS0 E) : f ∈ classS0' E :=
  let ⟨_, _, hrep⟩ := hf
  hrep.mem_classS0'

end LoewnerS0
