import LoewnerS0.StarlikeGen
import LoewnerS0.TaylorRec
import Mathlib.Analysis.Calculus.ContDiff.CPolynomial

/-!
# The second coefficient: the norm bound `2‖w‖²` fails in dimension two

The roadmap originally contained the statement `‖D²f(0)(w, w)/2‖ ≤ 2‖w‖²` for `f ∈ S⁰(𝔹)`. This is
false on the unit ball of `ℂ²`, even for starlike maps. The generator

  `h(z) = z + (5/2) z₁² e₂`

belongs to `M(𝔹²)`, since `(5/2)|z₁|²|z₂| < |z₁|² + |z₂|²` on `𝔹² \ {0}` (by
`27 a⁴ b² ≤ 4 (a² + b²)³`). The starlike map `f` it generates lies in `S*(𝔹²) ∩ S⁰(𝔹²)`, and the
Taylor recursion gives `D²f(0)(e₁, e₁)/2 = -h^[2](e₁) = -(5/2) e₂`, of norm `5/2 > 2`.

The correct statement (Graham–Hamada–Kohr–Kohr) bounds only the component in the direction of `w`:
`|⟨D²f(0)(w, w)/2, w⟩| ≤ 2‖w‖³`; see `LoewnerS0.Roadmap`. (The constant `5/2` can be pushed up to
`3√3/2` with the same example.)
-/

open Complex Metric Set Filter
open scoped InnerProductSpace Topology

noncomputable section

namespace LoewnerS0.SecondCoeff

/-- `ℂ²`, with coordinates numbered `0, 1`. -/
abbrev E2 := EuclideanSpace ℂ (Fin 2)

/-- the first coordinate `w ↦ w₁` -/
abbrev proj0 : E2 →L[ℂ] ℂ := PiLp.proj (𝕜 := ℂ) 2 (fun _ : Fin 2 => ℂ) 0

/-- `B(v, w) = (5/2) v₁ w₁ e₂`. -/
def Bq : ContinuousMultilinearMap ℂ (fun _ : Fin 2 => E2) E2 :=
  ((ContinuousMultilinearMap.mkPiAlgebra ℂ (Fin 2) ℂ).compContinuousLinearMap
    ![proj0, proj0]).smulRight (EuclideanSpace.single 1 (5 / 2 : ℂ))

lemma Bq_apply (v : Fin 2 → E2) : Bq v = (v 0 0 * v 1 0) • EuclideanSpace.single 1 (5 / 2 : ℂ) := by
  simp [Bq, Fin.prod_univ_two]

/-- The generator `h(z) = z + (5/2) z₁² e₂`. -/
def hq (z : E2) : E2 := z + Bq ![z, z]

lemma vec_two_eq (z : E2) : (![z, z] : Fin 2 → E2) = fun _ => z := by
  funext i; fin_cases i <;> rfl

lemma norm_Bq_le (z : E2) : ‖Bq ![z, z]‖ ≤ ‖Bq‖ * ‖z‖ ^ 2 := by
  have := Bq.le_opNorm ![z, z]
  rw [vec_two_eq] at this ⊢
  simpa [Finset.prod_const] using this

lemma isCaratheodory_hq : IsCaratheodory hq := by
  have hdiff : Differentiable ℂ hq := by
    have h1 : Differentiable ℂ (fun z : E2 => Bq (fun _ => z)) :=
      (Bq.contDiff (n := 1)).differentiable one_ne_zero |>.comp
        (differentiable_pi.mpr fun _ => differentiable_id)
    have h2 : (fun z : E2 => Bq ![z, z]) = fun z : E2 => Bq (fun _ => z) := by
      funext z; rw [vec_two_eq]
    rw [show hq = fun z => z + Bq (fun _ => z) from funext fun z => by simp [hq, vec_two_eq]]
    exact differentiable_id.add h1
  have h0 : hq 0 = 0 := by
    simp only [hq, vec_two_eq, zero_add]
    exact Bq.map_coord_zero (m := fun _ => (0 : E2)) 0 rfl
  have hD : HasFDerivAt hq (ContinuousLinearMap.id ℂ E2) 0 :=
    hasFDerivAt_zero_of_norm_sub_le_sq one_pos h0 (C := ‖Bq‖) fun z _ => by
      simpa [hq] using norm_Bq_le z
  refine ⟨⟨hdiff.differentiableOn, h0, hD.fderiv⟩, fun z hz hz0 => ?_⟩
  -- `Re ⟪z, h z⟫ = ‖z‖² + Re (conj z₂ · (5/2) z₁²)`
  have hin : ⟪z, hq z⟫_ℂ = ⟪z, z⟫_ℂ + (starRingEnd ℂ) (z 1) * (5 / 2 * (z 0 * z 0)) := by
    rw [hq, inner_add_right, Bq_apply, inner_smul_right, EuclideanSpace.inner_single_right]
    simp only [Matrix.cons_val_zero, Matrix.cons_val_one]
    ring
  have hzz : (⟪z, z⟫_ℂ).re = ‖z‖ ^ 2 := by simpa using inner_self_eq_norm_sq (𝕜 := ℂ) z
  set a := ‖z 0‖ with ha
  set b := ‖z 1‖ with hb
  have hS : ‖z‖ ^ 2 = a ^ 2 + b ^ 2 := by
    rw [EuclideanSpace.norm_eq, Fin.sum_univ_two, Real.sq_sqrt (by positivity)]
  have hz1 : ‖z‖ < 1 := mem_unitBall.mp hz
  have hzpos : 0 < ‖z‖ := norm_pos_iff.mpr hz0
  have hS0 : 0 < a ^ 2 + b ^ 2 := by rw [← hS]; positivity
  have hS1 : a ^ 2 + b ^ 2 < 1 := by rw [← hS]; nlinarith
  -- the cubic term
  have hcub : |((starRingEnd ℂ) (z 1) * (5 / 2 * (z 0 * z 0))).re| ≤ 5 / 2 * (a ^ 2 * b) := by
    refine (Complex.abs_re_le_norm _).trans (le_of_eq ?_)
    simp only [norm_mul, Complex.norm_conj, norm_div, Complex.norm_ofNat, ← ha, ← hb]
    ring
  -- `(5/2) a² b < a² + b²` via `27 a⁴ b² ≤ 4 (a² + b²)³`
  have ha0 : 0 ≤ a := norm_nonneg _
  have hb0 : 0 ≤ b := norm_nonneg _
  have hkey : 27 * (a ^ 2) ^ 2 * b ^ 2 ≤ 4 * (a ^ 2 + b ^ 2) ^ 3 := by
    nlinarith [sq_nonneg (a ^ 2 - 2 * b ^ 2), mul_nonneg (sq_nonneg (a ^ 2 - 2 * b ^ 2))
      (by positivity : (0 : ℝ) ≤ 4 * a ^ 2 + b ^ 2)]
  have hsq : (5 / 2 * (a ^ 2 * b)) ^ 2 < (a ^ 2 + b ^ 2) ^ 2 := by
    have h1 : (5 / 2 * (a ^ 2 * b)) ^ 2 ≤ 25 / 27 * (a ^ 2 + b ^ 2) ^ 3 := by nlinarith
    have h2 : 25 / 27 * (a ^ 2 + b ^ 2) ^ 3 < (a ^ 2 + b ^ 2) ^ 2 := by
      have h3 : 0 < (a ^ 2 + b ^ 2) ^ 2 := by positivity
      nlinarith
    linarith
  have hlt : 5 / 2 * (a ^ 2 * b) < a ^ 2 + b ^ 2 := lt_of_pow_lt_pow_left₀ 2 hS0.le hsq
  rw [hin, Complex.add_re, hzz, hS]
  have := neg_abs_le ((starRingEnd ℂ) (z 1) * (5 / 2 * (z 0 * z 0))).re
  linarith

/-- The starlike map generated by `h(z) = z + (5/2) z₁² e₂`. -/
def fq : E2 → E2 := starlikeMap isCaratheodory_hq

lemma fq_mem_classSstar : fq ∈ classSstar E2 := starlikeMap_mem_classSstar isCaratheodory_hq

lemma fq_mem_classS0 : fq ∈ classS0 E2 := starlikeMap_mem_classS0 isCaratheodory_hq

/-- `D²f(0)(e₁, e₁)/2 = -(5/2) e₂`. -/
lemma second_coeff_fq :
    (2 : ℂ)⁻¹ • iteratedFDeriv ℂ 2 fq 0 (fun _ => e₁) = -Bq ![e₁, e₁] := by
  have key := (taylor_coeff_identities (f := fq) (h := hq) (B := Bq) (C := 0) (K := 0) (δ := 1)
    (isNormalized_starlikeMap isCaratheodory_hq)
    (fun z hz => fderiv_starlikeMap_apply isCaratheodory_hq hz) one_pos
    (fun z _ => by simp [hq]) e₁).1
  exact eq_neg_of_add_eq_zero_left key

lemma norm_second_coeff_fq : ‖(2 : ℂ)⁻¹ • iteratedFDeriv ℂ 2 fq 0 (fun _ => e₁)‖ = 5 / 2 := by
  rw [second_coeff_fq, norm_neg, Bq_apply]
  simp only [Matrix.cons_val_zero, Matrix.cons_val_one, e₁, PiLp.single_apply, ite_true]
  rw [one_mul, one_smul, PiLp.norm_single]
  norm_num

/-- **The norm bound `‖D²f(0)(w, w)/2‖ ≤ 2‖w‖²` fails in `S⁰(𝔹²)`.** -/
theorem not_classS0_second_coeff :
    ¬ ∀ f ∈ classS0 E2, ∀ w : E2,
      ‖(2 : ℂ)⁻¹ • iteratedFDeriv ℂ 2 f 0 (fun _ => w)‖ ≤ 2 * ‖w‖ ^ 2 := by
  intro H
  have h1 := H fq fq_mem_classS0 e₁
  rw [norm_second_coeff_fq] at h1
  have : ‖(e₁ : E2)‖ = 1 := by simp [e₁]
  rw [this] at h1
  norm_num at h1

/-- The same holds for starlike maps. -/
theorem not_classSstar_second_coeff :
    ¬ ∀ f ∈ classSstar E2, ∀ w : E2,
      ‖(2 : ℂ)⁻¹ • iteratedFDeriv ℂ 2 f 0 (fun _ => w)‖ ≤ 2 * ‖w‖ ^ 2 := by
  intro H
  have h1 := H fq fq_mem_classSstar e₁
  rw [norm_second_coeff_fq] at h1
  have : ‖(e₁ : E2)‖ = 1 := by simp [e₁]
  rw [this] at h1
  norm_num at h1

end LoewnerS0.SecondCoeff
