import LoewnerS0.Examples

/-!
# Unitary invariance

The classes `M(𝔹)` and `S⁰(𝔹)` are invariant under conjugation `f ↦ U⁻¹ ∘ f ∘ U` by unitary maps
`U : E ≃ₗᵢ[ℂ] E`. In particular every coefficient question about `S⁰(𝔹)` in a direction `u` can be
moved to a fixed direction, e.g. `e₁`.
-/

open Complex Metric Set Filter MeasureTheory
open scoped InnerProductSpace Topology

noncomputable section

namespace LoewnerS0

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E]

lemma mapsTo_unitBall (U : E ≃ₗᵢ[ℂ] E) : MapsTo U (unitBall E) (unitBall E) := fun z hz => by
  simpa [mem_unitBall] using hz

/-- The Carathéodory condition is invariant under conjugation by a unitary map `U`. -/
theorem IsCaratheodory.conj (U : E ≃ₗᵢ[ℂ] E) {h : E → E} (hh : IsCaratheodory h) :
    IsCaratheodory (fun z => U.symm (h (U z))) := by
  have hU := mapsTo_unitBall U
  have hhU : HasFDerivAt (fun z => h (U z))
      ((ContinuousLinearMap.id ℂ E).comp (U : E →L[ℂ] E)) 0 := by
    have : HasFDerivAt h (ContinuousLinearMap.id ℂ E) (U 0) := by
      simpa using hh.isNormalized.hasFDerivAt_zero
    exact this.comp 0 U.hasFDerivAt
  have hD : HasFDerivAt (fun z => U.symm (h (U z)))
      ((U.symm : E →L[ℂ] E).comp ((ContinuousLinearMap.id ℂ E).comp (U : E →L[ℂ] E))) 0 :=
    U.symm.hasFDerivAt.comp 0 hhU
  refine ⟨⟨?_, ?_, ?_⟩, ?_⟩
  · exact U.symm.differentiable.comp_differentiableOn
      (hh.isNormalized.differentiableOn.comp U.differentiable.differentiableOn hU)
  · simp [hh.map_zero]
  · rw [hD.fderiv]
    ext x
    simp
  · intro z hz hz0
    have hUz : U z ∈ unitBall E := hU hz
    have hUz0 : U z ≠ 0 := by simpa using hz0
    have e : ⟪z, U.symm (h (U z))⟫_ℂ = ⟪U z, h (U z)⟫_ℂ := by
      rw [U.inner_map_eq_flip]
    rw [e]
    exact hh.re_inner_pos (U z) hUz hUz0

/-- `M(𝔹)` is invariant under conjugation by a unitary map `U`. -/
theorem conj_mem_classM (U : E ≃ₗᵢ[ℂ] E) {h : E → E} (hh : h ∈ classM E) :
    (fun z => U.symm (h (U z))) ∈ classM E :=
  IsCaratheodory.conj U hh

/-- `S⁰(𝔹)` is invariant under conjugation by a unitary map `U`: if `f` is generated by the
Herglotz vector field `h` then `U⁻¹ ∘ f ∘ U` is generated by `U⁻¹ ∘ h(·, t) ∘ U`. -/
theorem conj_mem_classS0 [CompleteSpace E] (U : E ≃ₗᵢ[ℂ] E) {f : E → E}
    (hf : f ∈ classS0 E) : (fun z => U.symm (f (U z))) ∈ classS0 E := by
  obtain ⟨h, v, hh, hv, hlim⟩ := hf
  have hU := mapsTo_unitBall U
  let L : E →L[ℂ] E := U.symm.toContinuousLinearEquiv
  refine ⟨fun t z => U.symm (h t (U z)), fun t z => U.symm (v t (U z)), ⟨?_, ?_⟩, ?_, ?_⟩
  · intro t ht
    exact (hh.isCaratheodory t ht).conj U
  · intro z hz
    exact U.symm.continuous.comp_aestronglyMeasurable (hh.aestronglyMeasurable (U z) (hU hz))
  · intro z hz t ht
    obtain ⟨hmem, hint, heq⟩ := hv (U z) (hU hz) t ht
    simp only [LinearIsometryEquiv.apply_symm_apply]
    refine ⟨?_, ⟨L.integrable_comp hint.1, L.integrable_comp hint.2⟩, ?_⟩
    · simpa [mem_unitBall] using hmem
    · rw [heq, map_sub, LinearIsometryEquiv.symm_apply_apply]
      congr 1
      exact (U.symm.toLinearIsometry.intervalIntegral_comp_comm (fun s => h s (v s (U z)))).symm
  · intro z hz
    have := (U.symm.continuous.tendsto _).comp (hlim (U z) (hU hz))
    simpa [Function.comp_def] using this

end LoewnerS0
