import LoewnerS0.Cex.Taylor
import LoewnerS0.Starlike
import LoewnerS0.StarlikeGen
import LoewnerS0.TaylorRec

/-!
# The counterexample: a starlike map of `𝔹²` with `a₃,₀ > 3`

Theorem 1.1 of `disproof_starlike.tex`. Everything specific to the example is proved:

* `isCaratheodory_hgen`: the generator `h(z) = U* H(U z)` belongs to `M(𝔹²)`
  (via the sum-of-squares certificate `Ffun_ge`, checked by the Lean kernel, and the sphere
  criterion `isCaratheodory_of_sphere`);
* `norm_hgen_taylor_le`: the Taylor expansion of `h` to order 3;
* `taylor_value`: the exact value `2863108143393914687/954177312400000000 = 3.000603877…`.

The two general facts of Loewner theory that connect `h` with the starlike map `f` it generates,
`StarlikeGeneration` and `TaylorRecursion`, are proved for every finite-dimensional complex inner
product space in `LoewnerS0.StarlikeGen` and `LoewnerS0.TaylorRec`. The theorem
`exists_classSstar_a30_gt_three_of` shows exactly how they are used;
`exists_classSstar_a30_gt_three` is the unconditional statement.
-/

open Complex
open scoped InnerProductSpace

noncomputable section

namespace LoewnerS0.Cex

/-- the exact value of `a₃,₀` -/
lemma a30_value_gt_three : (3 : ℝ) < 2863108143393914687 / 954177312400000000 := by norm_num

/-- **Theorem 1.1** (the starlike counterexample to `|a₃,₀| ≤ 3`), from the general results
`StarlikeGeneration` and `TaylorRecursion` of Loewner theory. -/
theorem exists_classSstar_a30_gt_three_of (hS : StarlikeGeneration E2)
    (hT : TaylorRecursion E2) : ∃ f ∈ classSstar E2, 3 < (a30 f e₁).re := by
  obtain ⟨f, hf, hfh⟩ := hS hgen isCaratheodory_hgen
  refine ⟨f, hf, ?_⟩
  have key := hT f hgen Bh Ch 136 (1 / 2) hf.1.1 isCaratheodory_hgen.isNormalized hfh
    (by norm_num) norm_hgen_taylor_le ea
  have ha : a30 f e₁ = (2863108143393914687 / 954177312400000000 : ℂ) := by
    unfold a30
    rw [show (e₁ : E2) = ea from rfl, key, EuclideanSpace.inner_single_left, map_one, one_mul,
      taylor_value]
  rw [ha]
  have : ((2863108143393914687 / 954177312400000000 : ℂ)).re =
      (2863108143393914687 / 954177312400000000 : ℝ) := by norm_num
  rw [this]
  exact a30_value_gt_three

/-- The starlike map generated by `h`: `f(z) = lim_{t → ∞} eᵗ φ_t(z)`, where `φ_t` is the flow
of `ż = -h(z)`. -/
def fstar : E2 → E2 := starlikeMap isCaratheodory_hgen

/-- The exact value of `a₃,₀` for the generated map. -/
theorem a30_fstar : a30 fstar e₁ = (2863108143393914687 / 954177312400000000 : ℂ) := by
  have key := taylorRecursion fstar hgen Bh Ch 136 (1 / 2)
    (isNormalized_starlikeMap isCaratheodory_hgen) isCaratheodory_hgen.isNormalized
    (fun z hz => fderiv_starlikeMap_apply isCaratheodory_hgen hz) (by norm_num)
    norm_hgen_taylor_le ea
  unfold a30
  rw [show (e₁ : E2) = ea from rfl, key, EuclideanSpace.inner_single_left, map_one, one_mul,
    taylor_value]

lemma three_lt_re_a30_fstar : 3 < (a30 fstar e₁).re := by
  rw [a30_fstar]
  have : ((2863108143393914687 / 954177312400000000 : ℂ)).re =
      (2863108143393914687 / 954177312400000000 : ℝ) := by norm_num
  rw [this]
  exact a30_value_gt_three

/-- **Theorem 1.1 of `disproof_starlike.tex`**: there is a normalized starlike map `f` of the unit
ball of `ℂ²` with `a₃,₀(f) = 2863108143393914687/954177312400000000 = 3.000603877… > 3`. -/
theorem exists_classSstar_a30_gt_three : ∃ f ∈ classSstar E2, 3 < (a30 f e₁).re :=
  ⟨fstar, starlikeMap_mem_classSstar isCaratheodory_hgen, three_lt_re_a30_fstar⟩

/-- The same map has parametric representation: there is `f ∈ S⁰(𝔹²)` with `a₃,₀(f) > 3`. -/
theorem exists_classS0_a30_gt_three : ∃ f ∈ classS0 E2, 3 < (a30 f e₁).re :=
  ⟨fstar, starlikeMap_mem_classS0 isCaratheodory_hgen, three_lt_re_a30_fstar⟩

end LoewnerS0.Cex
